import 'package:get/get_navigation/src/root/internacionalization.dart';

class XStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          'account': '账号',
          'password': '密码',
          'signin': '登录',
          'home' : "首页",
          'categories' : "分类",
          'cart' : "购物车",
          'my_account' : "我的账户",
          'special' : "专题",
          'parts' : "配件",
          'original_price' : "原价",
          'current_price' : "现价",
          'group_formation' : "成团",
          'reduction' : "立减",
          'no_data' : "暂无数据",
          'good_detail' : "商品详情",
          'commodity_parameters' : "商品参数",
          'common_problem' : "常见问题",
          'add_cart' : "加入购物车",
          'buy' : "立即购买",
          'price' : "价格",
          'specifications' : "规格",
          'number' : "数量",
          "already_selected": "已选择",
          "total": "合计",
          "cancel": "取消",
          "confirm": "确认",
          "tips": " 提示",
          "delete": "删除",
          "location_manager": "地址管理",
          "about_us": "关于我们",
          "add_address": "添加地址",
          "edit": "编辑",
          "pay": "付款",
          "all": "全部",
          "orders": "订单",
          "delete_success": "删除成功",
          "cancel_success": "取消成功",
          "order_delete_tips": "是否确认删除此订单",
          "order_cancel_tips": "是否确认取消此订单",
          "already_cancel": "已取消",
          "pending_payment": "待付款",
          "pending_shipment": "待发货",
          "pending_receipt": "待收货",
          "completed": "已完成",
          "footprint": "足迹",
          "feedback": "反馈",
          "recommend": "推荐产品",
          "register_now": "立即注册",
          "register": "注册",
          "welcome": "欢迎",
          "submit_order": "提交订单",
          "register_success": "注册成功",
          "company": "公司",
          "logout": "退出登录",
          "login": "登录",
          "submit_success": "提交成功",
          "order_details": "订单详情",
          "loading": "正在加载中...",
          "agent": "代理商",
          "dealer": "经销商",
          "invite_code": "邀请码",
          "sales_mode": "销售模式",
          "please_select": "请选择",
          "view_all": "查看全部",
          "confirm_logout": "确认退出当前账号吗？",
          "go_settle": "去结算",
          "edit_address":"编辑地址",
          "address_please_input_name":"请输入收货人姓名",
          "address_please_input_phone":"请输入收货人电话",
          "address_please_input_correct_phone":"请输入正确的收货人电话",
          "address_please_select_city":"请选择省/市/区",
          "address_please_input_detail":"请输入街道门牌、楼栋房号等信息",
          "address_set_default": "设为默认地址",
          "address_delete_tips": "确定删除此地址信息吗?",
          "fill_in_order": "填写订单",
          "remark": "备注",
          "goods_total": "商品合计",
          "coupon_total": "优惠合计",
          "freight": "运费",
          "actual_pay": "实付",
          "check_bill": "查看订单",
          "back_home": "返回首页",
          "order_number": "订单号码",
          "order_time": "下单时间",
          "commission": "佣金",
          "order_status": "订单状态",
          "delete_fail": "删除失败",
          "featured_categories": "按类别购物",
          "special_offers": "热销产品",
          "featured_products": "限时抢购",
          "product": "产品",
          "vendor": "供应商",
          "new_arrivals": "新品到货",
          'message' : "消息",
          'wishlist' : "愿望清单",
          'inquiry' : "询盘",
          'help_center' : "帮助中心",
          "keyword": "关键词",
        },
        'en_US': {
          'username': 'Username',
          'password': 'Password',
          'signin': 'Sign in',
          'home' : "home",
          'categories' : "Category",
          'cart' : "Cart",
          'message' : "Message",
          'my_account' : "My account",
          'special' : "Special",
          'parts' : "Parts",
          'original_price' : "Original price",
          'current_price' : "Current price",
          'group_formation' : "Group formation",
          'reduction' : "Reduction",
          'no_data' : "No data",
          'good_detail' : "Good detail",
          'commodity_parameters' : "Commodity parameters",
          'common_problem' : "Common problem",
          'add_cart' : "Add cart",
          'buy' : "Buy",
          'price' : "Price",
          'specifications' : "Specifications",
          'number' : "Number",
          "already_selected": "Already selected",
          "total": "Total",
          "cancel": "Cancel",
          "confirm": "Confirm",
          "tips": " Tips",
          "delete": "Delete",
          "location_manager": "Location manager",
          "about_us": "About us",
          "edit": "Edit",
          "pay": "Pay",
          "all": "All",
          "my_order": "Orders",
          "delete_success": "Delete success",
          "cancel_success": "Cancel success",
          "order_delete_tips": "Are you sure to delete this order",
          "order_cancel_tips": "Are you sure to cancel this order",
          "already_cancel": "Already cancel",
          "pending_payment": "Pending payment",
          "pending_shipment": "Pending shipment",
          "pending_receipt": "Pending receipt",
          "completed": "Completed",
          "footprint": "Footprint",
          "feedback": "Feedback",
          "recommend": "Featured Product",
          "register_now": "Register now",
          "register": "Register",
          "welcome": "Welcome",
          "submit_order": "Submit",
          "register_success": "Register success",
          "company": "Company",
          "logout": "Logout",
          "login": "Login",
          "submit_success": "Submit success",
          "order_details": "Order detail",
          "loading": "Loading...",
          "agent": "Agent",
          "dealer": "Distributor",
          "invite_code": "Invite code",
          "sales_mode": "Sales model",
          "please_select": "Please select",
          "view_all": "View all",
          "confirm_logout": "Are you sure to logout？",
          "go_settle": "Go settle",
          "edit_address":"Edit Address",
          "address_please_input_name": "Please input recipient's name",
          "address_please_input_phone": "Please input recipient's phone number",
          "address_please_input_correct_phone":
              "Please input right recipient's phone number",
          "address_please_select_city": "Please select city",
          "address_please_input_detail": "Please input detailed address",
          "address_set_default": "Set as default address",
          "address_delete_tips": "Are you sure to delete address?",
          "fill_in_order": "Fill in order",
          "remark": "Remark",
          "goods_total": "Goods total",
          "coupon_total": "Coupon total",
          "freight": "Freight",
          "actual_pay": "Actual pay",
          "check_bill": "Check bill",
          "back_home": "Back to home page",
          "order_number": "Order number",
          "order_time": "Order time",
          "commission": "Commission",
          "order_status": "Order status",
          "delete_fail": "Delete fail",
          "featured_categories": "Featured Categories",
          "special_offers": "Best Sellers For Your Stock Car",
          "featured_products": "Featured Products",
          "new_arrivals": "New Arrivals",
          'wishlist' : "Wishlist",
          'inquiry' : "Inquiry",
          'help_center' : "Help Center",
          "product": "Product",
          "vendor": "Vendor",
          "keyword": "Keyword",
        }
      };
}
